name: main

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn run all
      - run: yarn run format-check
        if: always()
      - run: yarn run lint-check
        if: always()
      - run: yarn run style-check
        if: always()
