name: main

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/**'

jobs:
  CI:
    uses: ./.github/workflows/ci.yml

  test:
    uses: ./.github/workflows/test.yml
    with:
      coverage: true
